# Brings up elasticsearch cluster, FluentD logger & Kibana interface
version: "2"
services:
  nginx:
    image: nginx
    container_name: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
     - ${CERTS_PATH}:/etc/nginx/certs:ro  # CERTS_PATH must be a path to a writable host volume. It stores the LE certificates.
     - /etc/nginx/conf.d
     - /etc/nginx/vhost.d
     - /usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes_from:
      - nginx
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: -notify-sighup nginx -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    links:
      - nginx
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
#    build: letsencrypt
    container_name: nginx-letsencrypt
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - DEBUG=false
    volumes_from:
      - nginx
    volumes:
      - ${CERTS_PATH}:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
  # Elasticsearch cluster setup for Master Node
  elasticsearch:
    build: elasticsearch/
    container_name: elasticsearch
    environment:
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    networks:
      - esnet

  # Elasticsearch slave node
  elasticsearch_node1:
    build: elasticsearch/
    container_name: elasticsearch_node1
    environment:
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    links:
      - elasticsearch
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

  # Bring up fluentd Listeneer
  fluentd:
    container_name: fluentd
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    depends_on:
      - elasticsearch
    ports:
      - 127.0.0.1:24224:24224
      - "24224:24224/udp"
    networks:
      - esnet
  
  # Bring up Kibana container
  kibana:
    build: kibana/
    container_name: kibana
    ports:
      - 127.0.0.1:5605:5605
      # - 127.0.0.1:5601:5601
    expose:
      - 5601
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=5601
    networks:
      - esnet
# Shared volumes between elastic search
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

# Use comman network interface esnet between all containers
networks:
  esnet:
    driver: bridge
